version: "3.8"

services:
  app:
    container_name: app
    image: yaraslava/home-library-service:app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - db:/var/lib/postgresql/data
      - ./src:/app/src/
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - service_default

  database:
    container_name: database
    image: yaraslava/home-library-service:db
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - service_default

volumes:
  db:

networks:
  service_default:
    driver: bridge
